import "~/styles/globals.css";

import localFont from "next/font/local";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Footer from "./_components/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// load font
const googleGEO = localFont({
  src: "../../public/fonts/Geo-Regular.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body
        className={`${googleGEO.className} bg-black text-2xl text-white`}
      >
        <TRPCReactProvider>{children}</TRPCReactProvider>

        <Footer />
      </body>
    </html>
  );
}
